In [1]:
import pandas as pd
import numpy as np

In [2]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 43.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [3]:
from sqlalchemy import create_engine
database_url = "postgresql://etl_user:tHTK9P4jdQKFnizhnafqha180KVOLlCf@dpg-d6qu5n6uk2gs73fspecg-a.oregon-postgres.render.com/etl_seguros_uami"
engine = create_engine(database_url)

In [4]:
#en esta subieremos el raw
url = "https://raw.githubusercontent.com/AlexisG81/etl-data-pipeline-2516232022/refs/heads/main/data/raw/F_pedidos.csv"

pedidos = pd.read_csv(url)

In [5]:
pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_pedido     236 non-null    object
 1   id_cliente    230 non-null    object
 2   fecha_pedido  231 non-null    object
 3   monto         230 non-null    object
 4   estado        236 non-null    object
dtypes: object(5)
memory usage: 9.3+ KB

In [7]:
pedidos.isnull().sum()

id_pedido       0
id_cliente      6
fecha_pedido    5
monto           6
estado          0
dtype: int64

In [9]:
pedidos.duplicated().sum()

np.int64(6)

In [10]:
#Normalizar columnas

def normalizar_columnas(df):
  df.columns =(
      df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ","_")
  )
  return df

In [11]:
#Limpiar texto

def limpiar_texto(df):

  for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].replace(
        ["nan","None","Null","null",""],
        pd.NA
        )
    return df

In [12]:
pedidos = normalizar_columnas(pedidos)
pedidos = limpiar_texto(pedidos)
pedidos = pedidos.drop_duplicates()

In [13]:
#Eliminar Duplicados
def eliminar_duplicados(df):
    return df.drop_duplicates()

In [16]:
#convertir fecha a datetime
pedidos["fecha_pedido"] = pd.to_datetime(
    pedidos["fecha_pedido"].astype(str).str.strip(),
    errors="coerce",
    dayfirst=True
)

/tmp/ipykernel_14919/536916495.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  pedidos["fecha_pedido"] = pd.to_datetime(

In [18]:
pedidos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 230 entries, 0 to 229
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_pedido     230 non-null    object
 1   id_cliente    224 non-null    object
 2   fecha_pedido  212 non-null    datetime64[ns]
 3   monto         224 non-null    object
 4   estado        230 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 10.8+ KB

In [19]:
#convertir monto en float
pedidos["monto"] = (

   pedidos["monto"]
   .astype(str)
   .str.replace(",",".",regex=False)
)

#Convertir decimal
pedidos["monto"] = pd.to_numeric(
    pedidos["monto"],
    errors="coerce"
)

In [21]:
columnas_obligatorias = [
    "id_pedido",
    "id_cliente",
    "fecha_pedido",
    "monto",
    "estado"
]

validos = pedidos [
 pedidos[columnas_obligatorias].notna().all(axis=1)
].copy()

rechazados = pedidos [
 pedidos[columnas_obligatorias].notna().all(axis=1)
].copy()

In [22]:
def motivo_rechazo(row):
    motivos = []

    if pd.isna(row["id_pedido"]):
        motivos.append("id_pedido_nulo")

    if pd.isna(row["id_cliente"]):
        motivos.append("id_cliente_nulo")

    if pd.isna(row["fecha_pedido"]):
        motivos.append("fecha_pedido_nulo")

    if pd.isna(row["monto"]):
        motivos.append("monto_nulo")

    if pd.isna(row["estado"]):
        motivos.append("estado_nulo")

    return ", ".join(motivos)

# APLICAR MOTIVOS A LOS RECHAZADOS
rechazados["motivo_rechazo"] = rechazados.apply(motivo_rechazo, axis=1)

In [24]:
validos.to_csv("pedidos_curated.csv", index=False)
rechazados.to_csv("pedidos_rejects.csv", index=False)

In [25]:
validos.head()

  id_pedido id_cliente fecha_pedido    monto       estado
0   PED7000     CL1138   2024-11-28  1984.03     enviado
2   PED7002     CL1067   2024-07-13   433.46    cancelado
3   PED7003     CL1097   2025-05-02   352.01    cancelado
4   PED7004     CL1068   2024-12-20  1182.84      enviado
5   PED7005     CL1030   2024-04-02  2154.60  preparacion

In [26]:
validos.dtypes

id_pedido               object
id_cliente              object
fecha_pedido    datetime64[ns]
monto                  float64
estado                  object
dtype: object

In [27]:
validos.isnull().sum()

id_pedido       0
id_cliente      0
fecha_pedido    0
monto           0
estado          0
dtype: int64

In [28]:
validos.value_counts()

id_pedido  id_cliente  fecha_pedido  monto    estado
PED7000    CL1138      2024-11-28    1984.03  enviado        1
PED7002    CL1067      2024-07-13    433.46   cancelado      1
PED7003    CL1097      2025-05-02    352.01   cancelado      1
PED7004    CL1068      2024-12-20    1182.84  enviado        1
PED7005    CL1030      2024-04-02    2154.60  preparacion    1
                                                            ..
PED7224    CL1100      2024-10-31    2234.22   entregado     1
PED7225    CL1118      2024-11-11    459.90   cancelado      1
PED7227    CL1001      2024-09-30    65.82    preparacion    1
PED7228    CL1119      2025-01-14    1464.83  pendiente      1
PED7229    CL1058      2024-10-14    2220.16  preparacion    1
Name: count, Length: 190, dtype: int64